# -*- coding: utf-8 -*-
"""FormatedData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aO8xFS5xDCuBWL1ogGDHoQlDm6Ox8oEd
"""

import os
import pandas as pd

def format_data(file):
  f = open (file,'r')
  mensaje = f.read()
  data=[]
  val=''
  for i in mensaje:
    
    if i=='\n':
      data.append(float(val))
      val=''
    else:
      val+=i
  #data.append(float(val))
  f.close()
  return data

def delete_wors_best(data,n):
  databest=data.copy()
  dataworst=data.copy()
  databest.sort()
  dataworst.sort(reverse=True)
  dataEliminate=dataworst[0:n]+databest[0:n]
  dataReturn=[]
  for i in data:
    if i not in dataEliminate:
      dataReturn.append(i)
    else:
      dataEliminate.remove(i)
  return dataReturn[0:30]


def dividir_por_hilos(conten):
  hilos={'1':[],'2':[],'4':[]}
  for i in conten:
    root, extension = os.path.splitext(i)
    if extension =='.txt':
      hilos[root[-1]].append(root)
  return hilos


contenido = os.listdir('./')
writer = pd.ExcelWriter('datos.xlsx')
division=dividir_por_hilos(contenido)
for hilo in division:
  df=pd.DataFrame()
  for i in division[hilo]:
    results=format_data(i+'.txt')
    data=delete_wors_best(results,3)
    df.insert(0,i,data)
  df.to_excel(writer, sheet_name=hilo+' hilos', index=False)
writer.save()
writer.close()